### ISSUE TITLE
Demo code please

### ISSUE THREAD

**Issue by suntong** [dgryski/go-minhash#2]
Hi @dgryski, 

> This package works best when provided with a strong 64-bit hash function, such as CityHash, Spooky, Murmur3, or SipHash.

Would you give a simple demo code how to use the `go-minhash` with the recommended 64-bit hash function please? It's hard for newbies like me to put everything in places when they are new to both concepts. 

Thanks

**Comment by suntong** [comment]
pinnng~~~

**Comment by dgryski** [comment]
I should have some time to push some example tests tomorrow.

Thanks for your patience.

**Comment by suntong** [comment]
Oh, great to hear that. thanks.
